Algoritmo "circulo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/04/2025
Var
// Seção de Declarações das variáveis 
    raio, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Digite o valor do raio do circulo: ")
    leia(raio)
    
    area <- pi * exp(raio, 2)
    
    escreva("Area = ", area:02:03)

Fimalgoritmo